### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by bearded-avenger** [CGCookie/cgc-follow#1]
Hypothetical user - Bob
- [x] function to get a list/total of a Bob's followers
- [x] function to get a list/total of users Bob is following
- [x] function to check if bob is following userX
- [x] function to add a follower
- [x] function to remove a follower

helpers file - https://github.com/CGCookie/cgc-follow/blob/five/includes/helpers.php

**Comment by bearded-avenger** [comment]
too late already finished :)

**Comment by etcook** [comment]
You're a beast!
